# Generated by Django 5.2.8 on 2025-11-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformeResguardo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_serial', models.CharField(max_length=50)),
                ('report_datetime', models.DateTimeField()),
                ('engine_off_timestamp', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('is_safe', models.BooleanField()),
                ('distance_to_road_m', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
