# Generated by Django 5.2.8 on 2025-11-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informeresguardo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
